using ProyectoDIV1.Models;
using ProyectoDIV1.ViewModels;
using System;
using Xamarin.Forms;

namespace ProyectoDIV1.Views
{
    /// <summary>
    /// Interaction logic for inicio.xaml
	/// Generated by Export Kit - Lightning Storm.
    /// </summary>
    public partial class PerfilCandidato : ContentPage
    {
        public PerfilCandidato()
        {
            InitializeComponent();
            //BindingContext = new PersonViewModels();
<<<<<<< Updated upstream

        }

        private async void Registrarme_Clicked(object sender, EventArgs e)
        {
            Candidato candidato = new Candidato()
            {

               Nombre = nombre.Text,
               Apellido = apellido.Text,
               Email = email.Text,
               Ciudad = ciudad.Text,
               Celular = celular.Text,
               Edad = Int32.Parse(edad.Text),
               Curriculum = curriculum.Text,
               Foto = foto.Text
=======
>>>>>>> Stashed changes

            };
        }
    }
}
