using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Xamarin.Forms;
using ProyectoDIV1.ViewModels;

namespace ProyectoDIV1.Views
{
    /// <summary>
    /// Interaction logic for inicio.xaml
	/// Generated by Export Kit - Lightning Storm.
    /// </summary>
    public partial class PerfilCandidato : ContentPage
    {
        public PerfilCandidato()
        {
            InitializeComponent();
            BindingContext = new PersonViewModels();

        }
    }
}
	