using Xamarin.Forms;

namespace ProyectoDIV1.Views
{
    /// <summary>
    /// Interaction logic for inicio.xaml
	/// Generated by Export Kit - Lightning Storm.
    /// </summary>
    public partial class serviciosPersonas : ContentPage
    {
        public serviciosPersonas()
        {
            InitializeComponent();
        }
    }
}
